on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy
jobs:
  build:
    name: Hook
    runs-on: ubuntu-latest
    steps:

    - name: Start
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Sphinx Build
      uses: zhaoweiguo/sphinx-action@master
      with:
        docs-folder: "./"
        build-command: "make"

    - name: Clone documentation repo
      run: |
        git clone https://github.com/zhaoweiguo/knowledge.zhaoweiguo.com.git  --branch master --single-branch knowledge
        rm -rf ./knowledge/*
        cp -r build ./knowledge/
        rm -rf ./knowledge/build/doctrees
        cp -r index.html ./knowledge/
        cd ./knowledge
        mkdir -p ./0shares/_static/
        cp -r ../0shares/_static/images ./0shares/_static/
        git config --local user.email "zhaoweiguo@github.com"
        git config --local user.name "zhaoweiguo"
        git add .
        git commit -m "[github workflow knowledge]Update changes"  -a


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        directory: knowledge
        repository: 'zhaoweiguo/knowledge.zhaoweiguo.com'
        branch: master




    - name: Send dingding notify
      uses: zcong1993/actions-ding@master
      with:
        dingToken: ${{ secrets.DING_TOKEN }}
        secret: ${{ secrets.DING_SECRET }} # if secret set, action will call API with sign
        body: |
          {
            "msgtype": "link",
            "link": {
                "title": "GitHubAction",
                "text": "[GitHubAction]knowledge src is done!",
                "picUrl": "",
                "messageUrl": "https://knowledge.zhaoweiguo.com"
            }
          }




